mainapp/Tests/users/preferences_test.go
mainapp/graphql/private/generated.go
mainapp/graphql/private/models.go
mainapp/graphql/private/resolvers/preferences.graphqls
mainapp/graphql/private/resolvers/preferences.resolvers.go

- getOnePreference
- getAllPreferences
- updatePreferences
- Tests for all

Added preferences with Tests

---

frontend/src/App.js
frontend/src/components/EnviromentDropdown/index.jsx
frontend/src/components/Navbar/index.jsx
frontend/src/components/Sidebar/index.jsx
frontend/src/index.css

1.  Fixed layout being rendered for a second if a user tried to access a private route while not being logged in
2.  Fixed layout jumping around when scrolling the page up and down
3.  Fixed click effect being square when clicking on a sidebar menu
4.  Fixed Environment dropdown styling and functionality

Fixed layout issues

---

frontend/src/components/DrawerContent/AddUserDrawer/index.jsx
frontend/src/pages/TeamDetail.jsx

DA-48: Timezone text fields are fixed.

---

frontend/src/components/CustomSwitch/index.jsx
frontend/src/components/ThemeToggle/index.jsx

DA-51: Toggle theme integrated with DB.

---

frontend/src/Auth/LoginCallBack.jsx

Added default to "/" when redirectLocation is empty

DA-58: Fixed no RedirectLocation bug on login

---

frontend/.eslintignore
frontend/.eslintrc.js
frontend/package.json

Eslint will help centralize the formatting rules between all the the developers using the project. There may be some format changes we need to do on the existing files...

Development: Added ESLint to frontend

---

frontend/src/App.js
frontend/src/components/LoginForm/index.jsx

1.  Added marginTop to notistack
2. Added default "An error has occured" error message
3.  Fixed cancel icon not working

DA-44, DA-52 and DA-53: Notistack fixes

---

frontend/src/components/Navbar/index.jsx
frontend/src/utils/timeInTimezone.js

DA-57: Time in navbar is now live. Updates every second.

---

frontend/src/pages/Teams.jsx

DA-47: Table layout corrected.

---

frontend/src/App.js
frontend/src/components/UserDropdown/index.jsx
frontend/src/graphql/getUser.js
frontend/src/pages/MemberDetail.jsx
frontend/src/pages/Teams.jsx

Logout won't work until DA-55 is merged

DA-50: User drop down is ready.

---

frontend/src/components/DrawerContent/AddUserDrawer/index.jsx
frontend/src/graphql/createUser.js
frontend/src/graphql/getPlatform.js
frontend/src/pages/MemberDetail.jsx
frontend/src/pages/TeamDetail.jsx
frontend/src/pages/Teams.jsx
frontend/src/theme.js
mainapp/graphql/private/generated.go
mainapp/graphql/private/models.go
mainapp/graphql/private/resolvers/aa_platform.graphqls
mainapp/graphql/private/resolvers/aa_platform.resolvers.go
mainapp/graphql/private/resolvers/users.graphqls
mainapp/graphql/private/resolvers/users.resolvers.go

- Table is refreshed after a user is added
- Job title is being added to DB

DA-56: Add user behavior fixed

---

frontend/src/components/DrawerContent/AddUserDrawer/index.jsx

Change is at 1f2908461a24e01a29e16c20e96834eec632082e

DA-74: Add user bug

---

frontend/src/graphql/updateMe.js
frontend/src/graphql/updateUser.js
frontend/src/pages/MemberDetail.jsx

DA-68: updateUser front end hooked up to backend

---

frontend/src/pages/MemberDetail.jsx
frontend/src/pages/TeamDetail.jsx

- Remove bold from "Belongs to.."
- Scroll to top on load
- Disable deactivate, delete for logged in user

DA-85: Team details UI

---

mainapp/Tests/mainTest.go
mainapp/Tests/users/me_test.go

fixed timezone extra spacing bug

---

frontend/src/App.js
frontend/src/components/DrawerContent/AddEnvironmentDrawer/index.jsx
frontend/src/components/DrawerContent/DeactivateEnvironmentDrawer/index.jsx
frontend/src/components/DrawerContent/DeleteEnvironmentDrawer/index.jsx
frontend/src/components/Layout/Layout.component.jsx
frontend/src/graphql/addEnvironment.js
frontend/src/graphql/getEnvironment.js
frontend/src/graphql/getEnvironments.js
frontend/src/graphql/updateActivateEnvironment.js
frontend/src/graphql/updateDeactivateEnvironment.js
frontend/src/graphql/updateDeleteEnvironment.js
frontend/src/graphql/updateEnvironment.js
frontend/src/graphql/updatePlatform.js
frontend/src/pages/EnvironmentDetail.jsx
frontend/src/pages/Settings.jsx
frontend/src/theme.js
frontend/src/utils/drawerStyles.js
mainapp/Tests/Platform/environment_test.go
mainapp/database/models/platform.go
mainapp/graphql/private/generated.go
mainapp/graphql/private/models.go
mainapp/graphql/private/resolvers/aa_platform.graphqls
mainapp/graphql/private/resolvers/aa_platform.resolvers.go
mainapp/graphql/private/resolvers/permissions.resolvers.go
mainapp/graphql/private/resolvers/users.resolvers.go

1.  Added settings page - FRONTEND
2.  Added environment details page  - FRONTEND
3.  Added theming for drawer  - FRONTEND
4.  Added  "Description" field to environment model  - BACKEND
5.  Added  updateDeleteEnvironment mutation - BACKEND
6.  Added updateDeactivateEnvironment mutation - BACKEND
7.  Added updateActivateEnvironment mutation - BACKEND
8.  Added getEnvironment query - BACKEND
9.  Added tests to new environment mutations - BACKEND
10.  Added new queries and mutation to frontend - FRONTEND

DA-79 and DA-80: Added settings page and added theming for drawer

---

frontend/src/App.js

As discussed on teams, i've changed the notistack autoHideDuration from 60s to 30s

Changed notistack autoHideDuration to 30s

---

frontend/package.json
frontend/src/components/GetStartedForm/index.jsx
frontend/src/components/PasswordField/index.jsx
frontend/src/components/PasswordField/passwordField.css
frontend/src/pages/GetStarted.jsx

As discussed on teams
1.  Added timezone field selector
2.  Added password strength checker
3.  Replaced theme toggle
4.  Fixed other small ui changes based on wireframe

UI Changes - Get Started page

---

frontend/src/pages/EnvironmentDetail.jsx
frontend/src/pages/Settings.jsx

1.  Changed notistack message to say "Saved"
2.  Added scroll to top of the page
3.  Fixed environment table styling

DA-89, DA-90 and DA-91: Settings and environment details page

---

frontend/src/pages/TeamGroup/Members.jsx
frontend/src/pages/TeamGroup/Permissions.jsx
frontend/src/pages/TeamGroup/index.jsx

1. Remove platform permissions
2. Link users to team details page
3. Move environment info to top left

DA-98: Access group details page ready.

---

frontend/src/graphql/getUserEnvironments.js
frontend/src/pages/TeamDetail.jsx
mainapp/graphql/private/resolvers/aa_platform.resolvers.go
mainapp/graphql/private/resolvers/accessgroups.resolvers.go

1. Direct environments and access groups to their details on click
2. Add active, inactive chips
3. Disable add if input is empty

DA-99: Team details page is ready.

---

frontend/src/pages/AccessGroups.jsx

DA-106: Access group table: Display No access groups if there is no data.

---

frontend/src/App.js
frontend/src/components/GetStartedForm/index.jsx
frontend/src/components/Layout/Layout.component.jsx
frontend/src/components/ThemeToggle/index.jsx
frontend/src/pages/GetStarted.jsx

1.  Added error handling for when the server is down
2.  Fixed theme toggle weird styling
3.  Fixed page not navigating to another page after the user/platform is created
4.  Fixed theme changing on load
5.  Changed detail animation size and made it responsive
6.  Fixed get started page main layout (navbar is now fixed to the top)

Get started page UI fix

---

frontend/src/pages/AddSecret.jsx
frontend/src/pages/SecretDetail.jsx
mainapp/graphql/private/generated.go
mainapp/graphql/private/models.go
mainapp/graphql/private/resolvers/aa_platform.resolvers.go
mainapp/graphql/private/resolvers/accessgroups.graphqls
mainapp/graphql/private/resolvers/secrets.graphqls
mainapp/graphql/private/resolvers/secrets.resolvers.go

DA-112: Secrets page: description optional, duplicate key error.

---

frontend/src/components/GetStartedForm/index.jsx
frontend/src/components/PasswordField/index.jsx
frontend/src/components/PasswordField/passwordField.css
frontend/src/components/ThemeToggle/index.jsx

1.  Fixed user not logged in after sign up
2.  Fixed password strength checker color on dark mode
3. Changed theme toggle to be on frontend only(localStorage)

DA-108: Fixed user not logged in after sign up

---

frontend/src/components/DrawerContent/AddEnvironmentDrawer/index.jsx
frontend/src/components/DrawerContent/DeleteEnvironmentDrawer/index.jsx
frontend/src/components/EnviromentDropdown/index.jsx

1.  Now when a user adds a new environment, it will show on the environment dropdown right away
2. Now when a user removes an environment, it will be removed from the environment dropdown right away
3. Added validation to check if a user is trying to delete an environment that is currently selected

DA-121: Fixed adding new environment to the list when adding a new environment

---

frontend/package.json
frontend/src/App.js
frontend/src/components/CustomChip/index.jsx
frontend/src/components/CustomNodesContent/ApiNode/index.jsx
frontend/src/components/CustomNodesContent/ClearLogsNode/index.jsx
frontend/src/components/CustomNodesContent/PlayNode/index.jsx
frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/AddPipelinesPermissionDrawer/index.jsx
frontend/src/components/MoreInfoContent/ClearLogsNodeItem/index.jsx
frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/MoreInfoContent/RemoveLogsPageItem/index.jsx
frontend/src/components/MoreInfoMenu/index.jsx
frontend/src/components/Sidebar/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/index.css
frontend/src/pages/Pipelines.jsx
frontend/src/pages/PipelinesPermission.jsx
frontend/src/pages/RemoveLogs.jsx
frontend/src/theme.js
frontend/src/utils/checkActivePage.js
frontend/src/utils/customNodeStyle.js

1.  Added workflow page (it can be accessed by clicking on the pipeline table title)
2. Added pipelines permission page
How to access:

DA-103 and DA-104: Added workflow page and added permissions page

---

frontend/src/pages/Workers/WorkerDetail.jsx
frontend/src/pages/Workers/WorkerDetailMemory.jsx

Memory displays GB or MB

---

frontend/src/pages/Workers/Workers.jsx

Removed "idle" snackbar for worker groups

---

.devcontainer/devcontainer.json
app/go.mod
app/mainapp/Tests/workers/worker_groups_test.go
app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/aa_platform.resolvers.go
app/mainapp/graphql/private/resolvers/accessgroups.resolvers.go
app/mainapp/graphql/private/resolvers/permissions.resolvers.go
app/mainapp/graphql/private/resolvers/secrets.resolvers.go
app/mainapp/graphql/private/resolvers/users.resolvers.go
app/mainapp/graphql/private/resolvers/workers.graphqls
app/mainapp/graphql/private/resolvers/workers.resolvers.go
frontend/src/components/DrawerContent/SecretsDrawer/index.jsx
frontend/src/graphql/getWorkerGroupSecrets.js
frontend/src/pages/Workers/Workers.jsx

 DA-124: Worker groups secrets hook up to backend.

---

frontend/src/components/DrawerContent/SecretsDrawer/index.jsx
frontend/src/pages/Workers/WorkerDetail.jsx
frontend/src/pages/Workers/WorkerDetailCPU.jsx
frontend/src/pages/Workers/WorkerDetailMemory.jsx

Worker detail graph right aligned, manage secrets link added

---

frontend/src/pages/Workers/WorkerDetail.jsx

Corrected MB in memory details

---

app/mainapp/Tests/pipelines/pipelines_test.go
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Pipelines.jsx

DA-133: Pipeline page, connected count and filter. Added tests in the backend

---

frontend/src/components/EditorSidebar/index.jsx

Fixed bug where when you add in an extra python processor it tries to move the existing one

Processor drag and drop position fix

---

frontend/src/components/DrawerContent/AddPipelineDrawer/index.jsx

- Corrected alignment per wireframes
- Worker group selection is mandatory with red *

UI improvements for add pipeline drawer

---

frontend/src/pages/PipelinesPermission.jsx

Fixed icons not showing on mac

---

app/mainapp/Tests/pipelines/pipelines_specific_test.go
app/mainapp/Tests/pipelines/pipelines_test.go

Fixed tests

---

frontend/src/pages/View/StatusChips.jsx
frontend/src/pages/View/index.jsx

DA-149: Pipeline runs status chips ready.

---

frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/MoreInfoMenuPipeline/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Pipelines.jsx

DA-152: Pipelines table new UI ready.

---

frontend/src/components/CustomNodesContent/ApiNode/index.jsx
frontend/src/components/CustomNodesContent/BashNode/index.jsx
frontend/src/components/CustomNodesContent/CheckpointNode/index.jsx
frontend/src/components/CustomNodesContent/PlayNode/index.jsx
frontend/src/components/CustomNodesContent/PythonNode/index.jsx
frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/pages/View/StatusChips.jsx
frontend/src/pages/View/Timer.jsx
frontend/src/pages/View/useWebSocket.jsx

Added elapsed time to pipeline flows

---

frontend/src/pages/View/Timer.jsx

Snackbars removed from pipeline run/stop

---

frontend/src/components/DrawerContent/AddPipelineDrawer/index.jsx
frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/MoreInfoMenuPipeline/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Pipelines.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/View/StatusChips.jsx
frontend/src/pages/View/Timer.jsx
frontend/src/pages/View/index.jsx

Pipeline UI improvements

---

app/mainapp/Tests/pipelines/pipelines_test.go
app/mainapp/database/models/pipelines.go
app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/pipelines.graphqls
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/runpipelines.graphqls
app/mainapp/graphql/private/resolvers/runpipelines.resolvers.go
app/mainapp/pipelines/runpipeline.go
app/mainapp/routes/routes.go
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/graphql/getPipelineRuns.js
frontend/src/graphql/runPipelines.js
frontend/src/pages/Flow.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/View/Timer.jsx
frontend/src/pages/View/index.jsx
frontend/src/pages/View/useWebSocket.jsx

DA-153: Pipeline dropdown multiple runs complete.

---

frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/View/RunsDropdown.jsx

Changed order of runs to descending

---

frontend/src/App.js

DA-158: Added links for support and feedback

---

frontend/src/components/DrawerContent/LogsDrawer/AdjustIcon.jsx
frontend/src/components/DrawerContent/LogsDrawer/index.jsx
frontend/src/index.css

Running spinner icon now spins.

Pipeline Log running spinner icon spins.

---

app/mainapp/Tests/workers/worker_groups_test.go
app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/workers.graphqls
app/mainapp/graphql/private/resolvers/workers.resolvers.go
frontend/src/components/DrawerContent/AddPipelineDrawer/index.jsx
frontend/src/components/DrawerContent/ProcessTypeDrawer/index.jsx
frontend/src/components/DrawerContent/SecretsDrawer/index.jsx
frontend/src/graphql/addSecretToWorkerGroup.js
frontend/src/graphql/deleteSecretFromWorkerGroup.js
frontend/src/graphql/getSecretWorkerGroups.js
frontend/src/graphql/getWorkerGroupSecrets.js
frontend/src/graphql/getWorkerGroups.js
frontend/src/graphql/getWorkers.js
frontend/src/pages/Flow.jsx
frontend/src/pages/SecretDetail.jsx
frontend/src/pages/Workers/WorkerDetail.jsx
frontend/src/pages/Workers/Workers.jsx

Workers GraphQL environment changed from name to id.

DA-167: Update workers graphql environment

---

frontend/src/components/CustomNodesContent/CustomEdge/index.jsx
frontend/src/components/CustomNodesContent/CustomEdge/style.css
frontend/src/pages/Flow.jsx

Add remove edge button

---

frontend/src/graphql/getPipelineRuns.js
frontend/src/pages/Flow.jsx
frontend/src/pages/Pipelines.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/View/Timer.jsx
frontend/src/pages/View/useWebSocket.jsx

 DA-165 & DA-173 & & DA-174: Pipeline timer is displayed for completed runs. Last run displayed after an edit.

---

frontend/src/pages/View/index.jsx
frontend/src/pages/Workers/WorkerDetail.jsx

Update status chips

---

frontend/src/components/CustomNodesContent/BashNode/index.jsx
frontend/src/components/CustomNodesContent/PythonNode/index.jsx
frontend/src/components/DrawerContent/LogsDrawer/index.jsx
frontend/src/components/DrawerContent/LogsDrawer/useWebSocketLog.jsx
frontend/src/components/MoreInfoContent/ProcessTypeNodeItem/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Flow.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/View/useWebSocket.jsx

DA-176 & DA-177 & DA-178: Pipeline edit close redirects to view page. Logs graphql websockets calls fixed.

---

frontend/src/pages/Flow.jsx

update to schedule node data query

---

frontend/src/components/DrawerContent/SchedulerDrawer/Cron.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/RRule.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/Timezone.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/index.jsx
frontend/src/components/EditorSidebar/index.jsx
frontend/src/pages/View/index.jsx

Schedule per seconds tab ready.

---

app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/models.go
app/mainapp/graphql/private/resolvers/pipelines.graphqls
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/CronSecondsTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/CronTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/Timezone.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/index.jsx
frontend/src/components/EditorSidebar/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/graphql/getPipelines.js
frontend/src/pages/Flow.jsx

Schedule tab improvements. 

---

frontend/src/components/DrawerContent/SchedulerDrawer/CronTab.jsx
frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/MoreInfoContent/ProcessTypeNodeItem/index.jsx
frontend/src/components/MoreInfoContent/ViewPageItem/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Flow.jsx
frontend/src/pages/View/index.jsx

DA-187 Fix timezone tooltip
DA-189 Workers option removed from process node type menu
DA-191 Unable to turn on new pipeline bug fixed
DA-192 Pipeline edit on pipeline table connected.

DA-187, DA-189, DA-191, DA-192: Pipeline bug fixes

---

frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/View/index.jsx

View page pipeline status not refreshing bug fixed.

---

frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/View/RunsDropdown.jsx

- Duplicate flow dropdown fix
- Pipeline table search fix

Pipeline bugfixes

---

frontend/src/components/EnviromentDropdown/index.jsx

DA-201: Disabled dropdown for environment if there is only one.

---

frontend/src/pages/Settings.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/Workers/useWebSocket.jsx

- Removed dash from environment description on settings page
- Fixed a mui error.

Settings page UI fix

---

frontend/src/Auth/UserAuth.jsx
frontend/src/pages/Workers/WorkerDetail.jsx
frontend/src/pages/Workers/WorkerDetailCPU.jsx
frontend/src/pages/Workers/WorkerDetailMemory.jsx
frontend/src/pages/Workers/useWebSocket.jsx
frontend/src/utils/formatDate.js

Worker details refresh bugfix and UI improvements

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Changed editor tab behavior based on codeSandbox

Changed editor tab behavior

---

frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/useWebSocketLog.jsx
frontend/src/pages/Editor.jsx

Editor logs improvements

---

frontend/src/components/EditorPage/FileManager/index.jsx

DA-219: Code editor defaults to dp-entrypoint.py on load

---

frontend/src/components/EnviromentDropdown/index.jsx
frontend/src/components/Layout/Layout.component.jsx
frontend/src/components/UserDropdown/index.jsx
frontend/src/components/UserDropdown/styles.css

Navbar UI improvements

---

frontend/src/components/EditorPage/FileManager/index.jsx

File manager icon display on hover

---

frontend/src/pages/Deploy.jsx

Users gets navigated to deployments after clicking deploy

---

frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Deployments/DeploymentsTable.jsx

DA-254: Play button restored

---

frontend/src/graphql/getDeployment.js
frontend/src/graphql/getDeployments.js
frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/pages/Deployments/DeploymentsTableItem.jsx

'Turn off' is only displayed if a deployment is deploy_active

DA-255, DA-259: 'Deployed' chip is now driven by deploy_active

---

app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/deployments.graphqls
app/mainapp/graphql/private/resolvers/deployments.resolvers.go
frontend/src/graphql/getActiveDeployment.js
frontend/src/pages/Deploy.jsx

- Deployments table not showing latest after a deploy bug fixed.
- Online toggle switch removed for play trigger on deploy page.
- getDeployment renamed to getActiveDeployment

Renamed get deployment to get active deployment

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Unsaved circle is ready.

---

frontend/src/components/EditorPage/LogsColumn/index.jsx

Duplicate logs bug fixed.

---

app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/pipelines.graphqls
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
frontend/src/components/DrawerContent/DuplicatePipelineDrawer/index.jsx
frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/graphql/duplicatePipeline.js
frontend/src/pages/Flow.jsx

Duplicate pipeline hooked up to backend.

---

frontend/src/pages/Deployments/View/MenuItem.jsx
frontend/src/pages/Deployments/View/StatusChips.jsx
frontend/src/pages/Deployments/View/Timer.jsx
frontend/src/pages/Deployments/View/index.jsx

Run is hidden for old deployments

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Code editor log snackbars removed

---

frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/pages/Deployments/View/Timer.jsx

Run disabled for non-active deployments on deployment table

---

frontend/src/pages/Flow.jsx
frontend/src/pages/View/RunsDropdown.jsx
frontend/src/pages/View/Timer.jsx

Pipeline run triggers go green as the run begins

---

frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/EditorPage/FileManager/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/theme.js

DA-260, DA-226: Code editor dark theme integration complete

---

app/mainapp/Tests/pipelines/pipelines_test.go
app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/aa_platform.resolvers.go
app/mainapp/graphql/private/resolvers/accessgroups.resolvers.go
app/mainapp/graphql/private/resolvers/code_editor.resolvers.go
app/mainapp/graphql/private/resolvers/deployments.resolvers.go
app/mainapp/graphql/private/resolvers/permissions-pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/permissions.resolvers.go
app/mainapp/graphql/private/resolvers/pipelines.graphqls
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/piplinelogs.resolvers.go
app/mainapp/graphql/private/resolvers/secrets.resolvers.go
app/mainapp/graphql/private/resolvers/users.resolvers.go
app/mainapp/graphql/private/resolvers/workers.resolvers.go
frontend/src/App.js
frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/EditorPage/FileManager/index.jsx
frontend/src/components/MoreInfoContent/ProcessTypeNodeItem/index.jsx
frontend/src/graphql/getNode.js
frontend/src/index.css
frontend/src/pages/Editor.jsx
frontend/src/theme.js

- Fixed new file doesn't get uploaded bug
- File manager icons darker. Tab ripple removed
- Unsaved files can now be closed
- Editor backspace resetting to previous value bug fixed
- Tab height is slimmer
- Added getNode endpoint
- 'new folder' name is retained on new folders DA-222
- URI updated to have /\<pipelineID\>/\<nodeID\> DA-224
- Icons showing for all siblings in a folder bug fixed
- Added tooltips for add,delete,edit icons
- Spaces are now allowed for folder names

DA-260, DA-222, DA-224. DA-221: Code editor updates

---

frontend/src/components/EditorPage/PackagesColumn/index.jsx
frontend/src/pages/Editor.jsx
frontend/src/utils/editorLayouts.js

DA-265: Added packages container to editor page

---

app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/models.go
app/mainapp/graphql/private/resolvers/code_editor.graphqls
app/mainapp/graphql/private/resolvers/code_editor.resolvers.go
frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/EditorPage/PackagesColumn/index.jsx
frontend/src/graphql/getCodePackages.js
frontend/src/graphql/updateCodePackages.js
frontend/src/pages/Editor.jsx

DA-267: Python packages endpoints are ready.

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Added install button for python packages

---

frontend/src/components/EditorPage/FileManager/index.jsx

DA-268: Incorrect path bugfix.

---

frontend/src/components/EditorPage/FileManager/index.jsx

DA-266: Changed code editor tooltip position

---

frontend/src/pages/Editor.jsx

Code editor nodeName not showing bugfix

---

frontend/src/App.js

Learn link added

---

frontend/src/pages/Deployments/DeploymentRuns/index.jsx
frontend/src/pages/PipelineRuns/index.jsx

Create a pipeline by dragging.... text removed

---

frontend/src/components/DrawerContent/TurnOffPipelineDrawer/index.jsx
frontend/src/components/MoreInfoContent/PipelineTableItem/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Deployments/DeploymentRuns/index.jsx
frontend/src/pages/PipelineRuns/index.jsx

Pipeline turn on/off bugfix

---

frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Deployments/DeploymentRuns/GlobalDeploymentState.jsx
frontend/src/pages/Deployments/DeploymentRuns/StartStopRun.jsx
frontend/src/pages/Deployments/DeploymentRuns/useOnPageLoadWebSocket.jsx
frontend/src/pages/Deployments/DeploymentRuns/useOnRunWebSocket.jsx
frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/pages/PipelineRuns/GlobalRunState.jsx
frontend/src/pages/PipelineRuns/StartStopRun.jsx
frontend/src/pages/PipelineRuns/useOnPageLoadWebSocket.jsx
frontend/src/pages/PipelineRuns/useOnRunWebSocket.jsx

Temporary fix for deployment/pipeline run color update

---

frontend/src/components/DrawerContent/LogsDrawer/index.jsx
frontend/src/components/DrawerContent/LogsDrawer/useWebSocketLog.jsx
frontend/src/utils/formatDate.js

Added timezone to pipeline run logs

---

frontend/src/components/CustomNodesContent/BashNode/index.jsx
frontend/src/components/CustomNodesContent/PythonNode/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/components/MoreInfoContent/ProcessTypeNodeItem/index.jsx
frontend/src/components/MoreInfoContent/ViewPageItem/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Deployments/DeploymentRuns/EventRunButton.jsx
frontend/src/pages/Deployments/DeploymentRuns/MenuItem.jsx
frontend/src/pages/Deployments/DeploymentRuns/RunDepNavBar.jsx
frontend/src/pages/Deployments/DeploymentRuns/RunsDropdown.jsx
frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/pages/PipelineEdit.jsx
frontend/src/pages/PipelineRuns/EventRunButton.jsx
frontend/src/pages/PipelineRuns/RunNavBar.jsx
frontend/src/pages/PipelineRuns/RunsDropdown.jsx
frontend/src/pages/PipelineRuns/index.jsx

- Code menu removed from deployments
- Run buttons for pipelines are functional
- Run buttons for deployments are functional
- On first run errors and colors fixed for pipelines and deployments
- Node menu on editor page now displays correct menu

Pipeline run, run button connected on view page and pipeline table

---

frontend/src/pages/Deploy.jsx

Deploy worker group display fix

---

frontend/src/components/DrawerContent/ProcessTypeDrawer/index.jsx

Pipeline edit node workergroup shows name instead of 'default'

---

frontend/src/pages/Deploy.jsx

Deploy online switch for play trigger fixed.

---

frontend/src/components/DrawerContent/AddUserDrawer/index.jsx

Add user UI update

---

frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/CronTab.jsx

Added timezone to scheduler

---

frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx

UTC text trimmed

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

 Code editor fix

---

frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/CronSecondsTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/index.jsx
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/utils/cronZone.js
frontend/src/utils/formatDate.js

Pipelines table schedule now shows military time

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Code editor light mode background fixed

---

frontend/src/components/DrawerContent/TurnOffPipelineDrawerRunPipeline/index.jsx
frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/MoreInfoContent/ViewPageItem/index.jsx
frontend/src/pages/PipelineRuns/index.jsx

Pipeline run turn on/off button fixed

---

app/mainapp/Tests/permissions/access_groups_test.go
app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/resolvers/accessgroups.graphqls
app/mainapp/graphql/private/resolvers/accessgroups.resolvers.go
frontend/src/graphql/getMyAccessGroups.js
frontend/src/graphql/getMyPermissions.js
frontend/src/pages/MemberDetail.jsx

My permissions for non admin user hooked up to backend.

---

frontend/src/pages/Deployments/DeploymentRuns/RunsDropdown.jsx

Following error has been fixed

Fixed deployment run error if there is no run

---

app/mainapp/graphql/private/generated.go
app/mainapp/graphql/private/models.go
app/mainapp/graphql/private/resolvers/code_editor_run.resolvers.go
app/mainapp/graphql/private/resolvers/deployments.graphqls
app/mainapp/graphql/private/resolvers/deployments.resolvers.go
app/mainapp/graphql/private/resolvers/pipelines.graphqls
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/graphql/getDeployments.js
frontend/src/graphql/getPipelines.js
frontend/src/pages/Deployments/DeploymentsTable.jsx

Pipeline table time zone text

---

frontend/src/components/EnviromentDropdown/index.jsx

Environment dropdown width fix

---

frontend/craco.config.js
frontend/src/components/EditorPage/EditorColumn/index.jsx

Code highlight on refresh issue has been fixed.

Code highlight fix

---

frontend/src/components/EnviromentDropdown/index.jsx

Environment dropdown update

---

frontend/src/pages/TeamDetail.jsx
frontend/src/pages/TeamGroup/Permissions.jsx
frontend/src/pages/TeamGroup/index.jsx

Team detail UI improvements

---

frontend/src/pages/MemberDetail.jsx
frontend/src/pages/TeamDetail.jsx
frontend/src/pages/TeamGroup/Permissions.jsx
frontend/src/pages/TeamGroup/index.jsx
frontend/src/utils/formatString.js

Special permissions UI update

---

frontend/package.json
frontend/src/pages/PipelineEdit.jsx
frontend/src/utils/PipelinePrepareGraphInput.js

Added set auto flow layout if node positions are {x:0,y:0}

---

frontend/src/pages/Workers/WorkerDetail.jsx

Environment change on details page causes redirect to worker group page

Worker groups detail page update. Issue #331

---

app/mainapp/graphql/private/resolvers/accessgroups.resolvers.go
app/mainapp/graphql/private/resolvers/permissions-pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/pipelines.resolvers.go
app/mainapp/graphql/private/resolvers/runpipelines.resolvers.go
app/mainapp/graphql/private/resolvers/users.resolvers.go
frontend/src/pages/PipelineRuns/EventRunButton.jsx
frontend/src/pages/PipelineRuns/index.jsx

Permissions clean up

---

cypress/cypress.config.js
cypress/cypress/e2e/dataplane/08-create-pipeline.cy.js
cypress/cypress/e2e/dataplane/14-deployment.cy.js
frontend/src/pages/Deployments/DeploymentsTable.jsx
frontend/src/pages/Deployments/DeploymentsTableItem.jsx
frontend/src/pages/PipelineEdit.jsx

Added deployment turn off cypress test.

Deployment cypress test

---

app/workers/cmetric/cgroupv2/main.go
frontend/src/components/DrawerContent/AddPipelineDrawer/index.jsx

Display error if there are no running workers in an environment for new pipelines

Display error for missing worker group

---

frontend/src/components/DrawerContent/LogsDrawer/index.jsx
frontend/src/components/EditorPage/InstallationLogsColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/pages/Deployments/DeploymentRuns/LogsDrawer/index.jsx

Added selectableLines to lazylog

---

frontend/src/components/EditorPage/EditorColumn/index.jsx

Fixed unsaved changes circle bug

---

app/mainapp/routes/routes.go
frontend/src/components/EditorPage/EditorColumn/index.jsx

New file now gets its ID from the backend

Failing to delete newly created file issue fixed

---

frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/useWebSocketLog.jsx

Code editor run log's time is on user's timezone

---

frontend/src/components/TableContent/PipelineTable/index.jsx

Added plug icon for api triggers

---

frontend/src/components/DrawerContent/EditorDrawers/APITriggerDrawer/index.jsx

Fixed Dataplane_Endpoint for build version

---

app/mainapp/auth/apiauthmiddleware.go
app/mainapp/routes/routes.go
frontend/src/components/CustomNodesContent/ApiNode/index.jsx
frontend/src/components/DrawerContent/EditorDrawers/APITriggerDrawer/ApiKey.jsx
frontend/src/components/DrawerContent/EditorDrawers/APITriggerDrawer/index.jsx
frontend/src/components/EditorSidebar/index.jsx

Api trigger improvements

---

frontend/src/components/Layout/Layout.component.jsx
frontend/src/index.css

Scrollbar disabled for left sidebar

---

app/mainapp/routes/routes.go
frontend/src/components/DrawerContent/EditorDrawers/APITriggerDrawer/index.jsx

Api trigger paths updated

---

frontend/src/components/DrawerContent/LogsDrawer/index.jsx
frontend/src/components/EditorPage/InstallationLogsColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/index.css
frontend/src/pages/Deployments/DeploymentRuns/LogsDrawer/index.jsx

Updated logs UI

---

frontend/src/pages/Secrets.jsx

Secrets UX improved

---

frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawer/CronTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/CronSecondsTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/CronTab.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/IOSSwitch.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/Timezone.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/index.jsx
frontend/src/components/MoreInfoContent/ScheduleTriggerNodeItem/index.jsx
frontend/src/pages/PipelineEdit.jsx
frontend/src/pages/PipelineRuns/index.jsx

Scheduler UI fix - Scheduler can now be edited on the pipeline view page

---

frontend/src/components/DrawerContent/ProcessTypeDrawerRunPage/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/index.jsx
frontend/src/components/MoreInfoContent/ProcessTypeNodeItem/index.jsx
frontend/src/pages/PipelineRuns/index.jsx

Configure option for python nodes is now available on pipeline run page

---

app/mainapp/auth/apiauthmiddlewaredeployment.go
app/mainapp/routes/routes.go
frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/components/DrawerContent/DeployAPITriggerDrawer/index.jsx
frontend/src/components/DrawerContent/DeployAPITriggerTableDrawer/index.jsx
frontend/src/pages/Deploy.jsx

- Updated API trigger paths to include 'deployment' for deployments.
- Split auth middleware for deployment and pipeline API triggers into two.
- Removed Schedule edit option from deployments.

Deployment api fixes

---

cypress/cypress/e2e/dataplane/09-permission-manage-pipelines.cy.js
cypress/cypress/e2e/dataplane/14-add-remove-file.cy.js
frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/index.jsx
frontend/src/components/EditorPage/LogsColumn/useWebSocketLog.jsx
frontend/src/pages/Editor.jsx
frontend/src/utils/editorLayouts.js

Code run logs auto hide on run

---

frontend/src/components/EditorPage/EditorColumn/index.jsx
frontend/src/pages/Editor.jsx

Markdown editor defaults to view mode

---

frontend/src/components/CustomNodesContent/BashNode/index.jsx
frontend/src/components/CustomNodesContent/PythonNode/index.jsx
frontend/src/components/CustomNodesContent/ScheduleNode/index.jsx
frontend/src/pages/Deploy.jsx
frontend/src/pages/PipelineEdit.jsx
frontend/src/utils/customNodeStyle.js

Node improvements

---

frontend/package.json
frontend/src/App.js
frontend/src/components/EditorPage/Markdown/index.jsx

Added code highlighting and copy

---

cypress/cypress/e2e/dataplane/07-admin-permission.cy.js
cypress/cypress/e2e/dataplane/09-permission-manage-pipelines.cy.js
cypress/cypress/e2e/dataplane/11-permission-edit-all-pipelines-access-groups.cy.js
cypress/cypress/e2e/dataplane/12-permission-manage-pipelines-access-groups.cy.js
cypress/cypress/e2e/dataplane/14-add-remove-file.cy.js
cypress/cypress/e2e/dataplane/15-deployment.cy.js
cypress/cypress/e2e/dataplane/16-deploy-api-trigger.cy.js
cypress/package.json
cypress/yarn.lock

Cypress tests failure rate improved.

Cpress test improvements

---

frontend/src/components/DrawerContent/SchedulerDrawer/index.jsx
frontend/src/components/DrawerContent/SchedulerDrawerRunPage/index.jsx

Schedule text wording updated

---

frontend/src/components/TableContent/PipelineTable/index.jsx

Pagination is only displayed if there is more than one page.

Added pagination to pipeline table

---

frontend/src/pages/PipelineRuns/index.jsx

Pipeline run flow auto fits content

---

frontend/src/components/DrawerContent/ProcessTypeDrawer/index.jsx
frontend/src/pages/PipelineEdit.jsx

Added flow nodes unique name constraint

---

frontend/src/pages/PipelineRuns/index.jsx

Move cursor on logs bug fixed

---

frontend/src/pages/PipelineRuns/index.jsx

Flow nodes fit view max width set to 100%

---

frontend/src/components/DrawerContent/ProcessTypeDrawer/index.jsx
frontend/src/pages/PipelineEdit.jsx

This reverts commit 239747afe3b8064dd5ef849f05bb74fb244e644a.

Revert "Node unique name rollback"

---

cypress/cypress/e2e/dataplane/08-create-pipeline.cy.js

Updated pipeline flow to have 6 nodes

---

frontend/src/components/TableContent/PipelineTable/index.jsx
frontend/src/pages/PipelinesView.jsx

Fixed pipelines table ui bug

---

frontend/src/pages/Deployments/DeploymentRuns/RunDepNavBar.jsx
frontend/src/pages/PipelineRuns/RunNavBar.jsx

DA-292: Pipeline/Deployment stop button margin fixed

---

cypress/cypress.config.js
cypress/cypress/e2e/dataplane/17-rename-pipeline-nodes.cy.js

##Test Flow,
Add node, should default to python
Add node, should default to python 1, 
Rename to python, should error,
rename to python 1, should succeed
Click on python 1 rename to python 2, should succeed.
rename python 2 to python, should fail,
raname to python 3, should succeed.

Added pipeline node renaming test

---

frontend/src/pages/PipelineRuns/PipelineRunStructure.jsx
frontend/src/pages/PipelineRuns/RunsDropdown.jsx

Stale pipeline bugfix

---

frontend/src/pages/Editor.jsx

DA-301: React grid height is now responsive

---

.devcontainer/Dockerfile.dev
app/mainapp/code_editor/filesystem/file_create_processor.go
app/mainapp/database/migrations/db_migrate.go
cypress/Dockerfile.main.alpine
cypress/Dockerfile.workerpython.debian
cypress/Dockerfile.workerpython.ubuntu
docker-build/Dockerfile.main.alpine
docker-build/Dockerfile.workerpython.debian
docker-build/Dockerfile.workerpython.ubuntu
frontend/src/pages/Editor.jsx

- Code editor replay now defaults to 'Code editor'
- Failing to run before a pipeline run bug fixed

Default runid bugfix
